name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main # Change this to your main branch name if different (e.g., master)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24" # Use the Node.js version that matches your development environment
          cache: "npm" # Use npm if you're using npm instead of yarn

      - name: Install dependencies
        run: npm install --frozen-lockfile # Use npm ci if you're using npm

      - name: Build site
        run: npm run build # Use npm run build if you're using npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Change to your AWS region

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront distribution
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_SERVICES_DISTRIBUTION_ID }} --paths "/*"
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_ARTICLES_DISTRIBUTION_ID }} --paths "/*"
